pub const ENGLISH_MASCULINE_GIVEN_NAMES: &[&str] = &[
    "Aaron", "Abel", "Abraham", "Adam", "Adrian", "Alan", "Albert", "Alexander", "Alfred",
    "Andrew", "Anthony", "Arthur", "Asher", "Austin", "Benjamin", "Bernard", "Blake",
    "Brian", "Bruce", "Caleb", "Cameron", "Carl", "Charles", "Christian", "Christopher",
    "Clark", "Colin", "Connor", "Craig", "Daniel", "David", "Dennis", "Dominic", "Douglas",
    "Dylan", "Edward", "Edmund", "Elias", "Elijah", "Elliot", "Eric", "Ethan", "Evan",
    "Felix", "Francis", "Frank", "Frederick", "Gabriel", "Gareth", "George", "Graham",
    "Gregory", "Harold", "Harrison", "Harry", "Henry", "Howard", "Hugh", "Ian", "Isaac",
    "Jack", "Jacob", "James", "Jason", "Jeremy", "John", "Jonathan", "Joseph", "Joshua",
    "Julian", "Justin", "Keith", "Kenneth", "Kevin", "Lawrence", "Leonard", "Leo", "Lewis",
    "Liam", "Logan", "Louis", "Lucas", "Luke", "Malcolm", "Marcus", "Mark", "Martin",
    "Matthew", "Michael", "Miles", "Nathan", "Nathaniel", "Neil", "Nicholas", "Noah",
    "Oliver", "Oscar", "Owen", "Patrick", "Paul", "Peter", "Philip", "Quentin", "Ralph",
    "Raymond", "Reginald", "Richard", "Robert", "Roger", "Ronald", "Russell", "Ryan",
    "Samuel", "Scott", "Sean", "Sebastian", "Simon", "Spencer", "Stephen", "Steven",
    "Theodore", "Thomas", "Timothy", "Tristan", "Victor", "Vincent", "Walter", "William",
    "Zachary",

    "Aiden", "Alistair", "Anderson", "Archibald", "Bartholomew", "Beckett", "Benedict",
    "Bradley", "Brandon", "Callum", "Carter", "Cedric", "Chandler", "Clarence", "Clifford",
    "Cole", "Colton", "Curtis", "Damian", "Derek", "Desmond", "Donovan", "Edgar", "Edwin",
    "Emmett", "Ernest", "Eugene", "Finn", "Fletcher", "Francisco", "Franklin", "Geoffrey",
    "Gilbert", "Grant", "Hector", "Hollis", "Jasper", "Jeremiah", "Joel", "Jonah", "Jordan",
    "Judah", "Karl", "Keaton", "Kieran", "Landon", "Lester", "Lincoln", "Marshall",
    "Mason", "Maxwell", "Micah", "Mitchell", "Morgan", "Neil", "Norman", "Parker",
    "Percival", "Preston", "Quincy", "Randall", "Reuben", "Rowan", "Sawyer", "Sheldon",
    "Sterling", "Stuart", "Sylvester", "Terrence", "Tobias", "Trevor", "Vernon", "Warren",
    "Wesley", "Wilfred", "Zane",

    "Adolfo", "Alonzo", "Amos", "Anselm", "Anton", "Archer", "August", "Basil", "Blaine",
    "Brock", "Byron", "Cassius", "Cecil", "Cyrus", "Dante", "Dashiell", "Dexter", "Edric",
    "Ellis", "Emil", "Everett", "Fabian", "Fergus", "Gideon", "Hamish", "Ismael", "Julius",
    "Lachlan", "Leander", "Lloyd", "Lucian", "Magnus", "Merrill", "Niles", "Orlando",
    "Pascal", "Phineas", "Roderick", "Roland", "Roscoe", "Silas", "Thaddeus", "Ulysses",
    "Vaughn", "Wilbur", "Winston", "Xavier", "Yardley", "Zebedee",
];
